version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: one_theme_web
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432
